benchmark: iotest: openssl: fix for quark test

diff --git a/benchmarks/iotest/openssl/Makefile b/benchmarks/iotest/openssl/Makefile
--- a/benchmarks/iotest/openssl/Makefile
+++ b/benchmarks/iotest/openssl/Makefile
@@ -3,19 +3,39 @@ IMAGE_NAME=openssl-native-io
 CONTAINER_NAME=native-server
 PORT=4433
 RESULTS_FILE=native_benchmark_results.csv
+RUNTIME 	?= quark# Standart
+
+#
+# NOTE: it effects startup time but not performance
+#
+IGNORE_ATTESTATION ?= 1
+SRVARG =
 
 build:
 	docker build -f Dockerfile.native -t $(IMAGE_NAME) .
 
 run-server:
-	@echo "Starting Native OpenSSL Server..."
-	docker run -d --name $(CONTAINER_NAME) \
-		-p $(PORT):$(PORT) $(IMAGE_NAME) \
+	@if [ -n "$(IGNORE_ATTESTATION)" ]; then          \
+		SRVARG="-e Q_AA_NO_ATTEST=y";             \
+	else                                              \
+      		echo "Provide required arguments"; exit 1;\
+	fi;                                               \
+	if [ -n "$(RUNTIME)" ]; then 			  \
+      		RUNTIMEARG="--runtime=$(RUNTIME)";        \
+      		echo "Docker with runtime:$(RUNTIME)";    \
+	else						  \
+      		RUNTIMEARG="";			          \
+      		echo "Docker with runtime:runc";          \
+	fi;                                               \
+	echo "Starting Native OpenSSL Server...";         \
+	docker run -d --name $(CONTAINER_NAME)            \
+		--cpus=30 $$RUNTIMEARG $$SRVARG -p $(PORT):$(PORT) $(IMAGE_NAME) \
 		s_server -accept $(PORT) -WWW -cert cert.pem -key key.pem
 
 run-clients:
 	@echo "Size,Iteration,ConnPerUserSec,RealSec,Throughput_MBs" > $(RESULTS_FILE)
 	@for size_name in 1KB 2KB 4KB 8KB 16KB 32KB 64KB 128KB 256KB 512KB 1MB 2MB 4MB 8MB 16MB; do \
+		sleep 3; 					     \
 		echo ">>> Benchmarking Native Size: $$size_name..."; \
 		for i in {1..1000}; do \
 			RESULT=$$(openssl s_time -connect localhost:$(PORT) -www /files/$$size_name.bin -time 1 -new 2>&1); \
